### ISSUE TITLE
Skill-tree (Archer + Berserker) 

### ISSUE THREAD

**Issue by Snowawa** [AlanMorel/MapleServer2#13]
**Issue Description:**
The skills for Archer + Berserker seem to not allow points to be allocated for the first skill.

**Skill effected:**
**Archer**: Sharp Eyes + Eagle Claw
**Berserker**: Intimidation

**Example:**
Archer: https://i.imgur.com/P9sEVRK.png
Berserker: https://i.imgur.com/5oNRfaf.png

**Comment by rhydev** [comment]
The skill tree is missing skills entirely it seems, [here](https://arrowvulcan.github.io/MS2-Skill-Calculator/) is a reference of what it should look like. If possible can you check to ensure that all other classes are functioning properly aside from Archer and Berserker?

**Comment by rhydev** [comment]
This is fixed in [https://github.com/AlanMorel/MapleServer2/pull/25](https://github.com/AlanMorel/MapleServer2/pull/25), will close after merge.
