### ISSUE TITLE
2-handed weapons are rolled with 1-handed weapon values

### ISSUE THREAD

**Issue by Snowawa** [AlanMorel/MapleServer2#237]
**Example:**
A 2-handed weapon will at most have 5.6% Damage to Boss Enemies, or 1.6% piercing. 
The correct values should be 11.2% Damage to Boss Enemies, or 3.2% piercing.

Just need to 2x the values for the 1-handed weapons on the 2-handed.

**Comment by AngeloTadeucci** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/15664821/114942775-68884a00-9e1b-11eb-94b2-b6f9e4a6ba70.png)
![image](https://user-images.githubusercontent.com/15664821/114942787-6e7e2b00-9e1b-11eb-834e-710ad04f2c13.png)
