### ISSUE TITLE
Buying plot crashes / disconnects

### ISSUE THREAD

**Issue by Scantastic** [AlanMorel/MapleServer2#314]
Hi, buying a plot crashes / disconnects your character

**Comment by AngeloTadeucci** [comment]
Which branch you were in?

**Comment by Scantastic** [comment]
It's happening on the test server

**Comment by AngeloTadeucci** [comment]
@Scantastic can you try again? It should be good now.

**Comment by Scantastic** [comment]
Yep, it's good now, thank you!
