### ISSUE TITLE
Talking to Mino/opening Saved Special Hairstyles crashes client

### ISSUE THREAD

**Issue by Yukikosan** [AlanMorel/MapleServer2#339]
This doesn't happen every single time, but it has been happening frequently enough to where it should definitely be looked into if possible as it can be very frustrating, I can try to get a video showcasing this if needed since it seems to be a pretty randomly occuring bug.
It seems like this happens after around 3-4 times? after talking to him and bringing up the menu iirc, and I'm still not really sure why this is.

**Comment by AngeloTadeucci** [comment]
Can you see if this still happens after #340 ?

**Comment by Yukikosan** [comment]
I will give this another test and see if this still persists after the new database, if so I'll update it here

**Comment by AngeloTadeucci** [comment]
Issue has been fixed with #340
