### ISSUE TITLE
Triggers: initial cutscene soft lock

### ISSUE THREAD

**Issue by EcoIsMad** [AlanMorel/MapleServer2#359]
I started the server with the setup and with the help from a couple of users and it worked, after the log in i created the character and the game started normally.

The initial cutscene with is functional, but the next cutscene is compleately unusable, you can't skip the cutscenes and get soft locked after the cutscene.

The next images are all i found in the bug
![Screenshot (1042)](https://user-images.githubusercontent.com/75789336/131876824-7e4acbcf-6469-4007-95a1-6c9c3738a7d1.png)
![Screenshot (1044)](https://user-images.githubusercontent.com/75789336/131876900-e55bae80-81b7-4002-8681-83747bf34081.png)
![Screenshot (1048)](https://user-images.githubusercontent.com/75789336/131876921-4e6a07fd-30c8-406e-8589-2a54817b108a.png)
![Screenshot (1049)](https://user-images.githubusercontent.com/75789336/131876932-9479f8aa-c66a-49dc-921c-876d7b89d06e.png)
![Screenshot (1050)](https://user-images.githubusercontent.com/75789336/131876939-a9aca9f1-9a03-4927-bdff-fab54c713374.png)

**Comment by Zintixx** [comment]
Fixed in #366
