### ISSUE TITLE
Maple Navigator infinitely stuck on needing to claim Level Reward boxes

### ISSUE THREAD

**Issue by Yukikosan** [AlanMorel/MapleServer2#375]
The Maple Navigator is going through an infinitely repeating cycle of giving the player the option to claim the Level Reward boxes regardless of if the player has already claimed them beforehand; the counter will essentially reset back to the Level 10 Reward box and start the count all the way up to the Level 78 Reward box, even if they have already claimed every box before this "reset". Attempting to claim any Level Reward boxes after this reset will usually only give the current Level Reward box for the level it is stuck on yet nothing past this.

Example shown below: Attempting to claim the Level 10 Reward box will send it to the player's inventory as normal and will update to the next reward box on every new login as far as I'm aware and seen from my testing, but any attempts past this will not yield another box. The same goes for the Level 15 Reward box shown in the screenshots and every box that comes after it.
![MapleStory2_HpZSVb9tsD](https://user-images.githubusercontent.com/89223452/132608586-6e2122a2-791f-4f83-b8f8-0b01bde53172.png)
![MapleStory2_8f9hKjsFPv](https://user-images.githubusercontent.com/89223452/132608591-630ee821-81b6-4a37-bd5c-8fc62ae8034e.png)

**Comment by AngeloTadeucci** [comment]
I think this only happens when the server crashes because I can't reproduce by just saving it correctly

**Comment by Yukikosan** [comment]
that's so strange, I think you're right but then again I haven't tried to force the bug before so I could definitely try that.
if you have any ideas though, feel free to leave them here
