### ISSUE TITLE
Sky Fortress UI button does not work

### ISSUE THREAD

**Issue by gwagwaflamingo** [AlanMorel/MapleServer2#399]
Attempting to quickly teleport to Sky Fortress through the UI button (above UGC Workshop's button) does not work, even if quest Emergency Launch (91000013) is completed.

**Comment by AngeloTadeucci** [comment]
Completing quest 91000013 with an character on level 1, the button works so you can select Yes or No to teleport to Sky Fortress.
Completing quest 91000013 with an character on level 50, button says you need to complete "Emergency Launch".

I guess something is wrong with how we are updating the client

**Comment by AngeloTadeucci** [comment]
Should be fine with #622 .
Just make sure to complete the questline in order.
