### ISSUE TITLE
An System.OverflowException was thrown during running the server for a long period of time

### ISSUE THREAD

**Issue by Paper-Folding** [AlanMorel/MapleServer2#449]
### I hosted the Maple Server 2 in my remote server, and I have kept running it for about one day already. Tonight I log on my remote server only to find a `System.OverflowException` was thrown. I do not know how and why it was thrown, here I just provide the detail for this exception.
![image](https://user-images.githubusercontent.com/49343539/139581294-c7395fa7-13f3-49b1-aa67-7192d07121ed.png)

## The current and lastest console state(seems nothing wrong happened)
![image](https://user-images.githubusercontent.com/49343539/139581487-fbda6d04-2d6e-4eab-a137-6f7780977931.png)
![image](https://user-images.githubusercontent.com/49343539/139581854-cb81dfe6-bf9f-4d87-a0c1-8bf577e89ab4.png)
### I copy some of the lastest console log here in case you want:
```
[INFO] MapleServer2.Network.Server`1: "LoginServer" started on Port:20001
[DEBUG] MapleServer2.Network.Session: Handshake: 59 D6 13 00 00 00 01 00 0C 00 0
0 00 A6 64 AB B4 52 48 55 D6 0C 00 00 00 00
[INFO] MapleServer2.Network.Server`1: Client connected: LoginSession from ****
.195.239:54784
[INFO] MapleServer2.Network.Server`1: "LoginServer" started on Port:20001
[DEBUG] MapleServer2.Network.Session: Handshake: 66 61 13 00 00 00 01 00 0C 00 0
0 00 70 4A E0 D8 63 FE 6A 61 0C 00 00 00 00
[INFO] MapleServer2.Network.Server`1: Client connected: LoginSession from *****
3.47.155:56126
[INFO] MapleServer2.Network.Server`1: "LoginServer" started on Port:20001
[DEBUG] MapleServer2.Network.Session: Handshake: 1C 79 13 00 00 00 01 00 0C 00 0
0 00 80 9D 4F F6 45 D6 10 79 0C 00 00 00 00
```

### And I must appreciate it again for your dedicated hard work to make Maple Story 2 alive! Happy Halloween!

**Comment by AngeloTadeucci** [comment]
So I've seen this issue before and it looks like it happens when some specific type of ping request happens. 

In your console I can see different IPs doing the handshake with the server so it's probably some bot pinging every kind of possible IP and port combination for some reason. 

@darkvergus how about we just try catch the function and move on? Or try to check if the handshake contains the correct data, if there is any?
