### ISSUE TITLE
RequestItemUse deletes items it shouldn't

### ISSUE THREAD

**Issue by integralcoder95** [AlanMorel/MapleServer2#47]
Right now RequestItemUse always removes the item used from the inventory, however, some items are multi-use. Currently the biggest thing is affects is Instruments which disappear after a single use. Not sure how to check for it, possibly in the item metadata.
@rhydev

**Comment by rhydev** [comment]
Can you provide some screenshots of the specific interaction?

**Comment by rhydev** [comment]
Likely it is something that would need to be checked in item metadata as you suggest, but would like some screenshots just to make sure.

**Comment by bwu113** [comment]
I will look into it. prob has something to do with inventory handler.

**Comment by rhydev** [comment]
It would need to be parsed from the item meta data most likely, unless the packet includes the fact that it is multi-use.

**Comment by Zintixx** [comment]
This issue can be closed now, can't it? Doesn't seem like it's happening anymore.
