### ISSUE TITLE
[Tiny Bug Spotted] A dialog was popped out notifying you have already logged into the game, might relate to #462

### ISSUE THREAD

**Issue by Paper-Folding** [AlanMorel/MapleServer2#480]
### Last week you add a feature that can detect duplicate logins #462  , but this feature seems so good that it detect duplicate logins EVERY TIME I logged into the game:
![image](https://user-images.githubusercontent.com/49343539/141614947-36397291-6c6e-43f1-89a5-bec6b0866825.png)
### This is quite easy to re-produce, just login the game with your own account, and log off the game normally with the in-game menu, and re-launch the game, login the same account again, you'll find this dialog popping out several times.

**Comment by AngeloTadeucci** [comment]
This should be fixed with PR #486
