### ISSUE TITLE
Exception with negative size header size

### ISSUE THREAD

**Issue by darkvergus** [AlanMorel/MapleServer2#490]
![image](https://user-images.githubusercontent.com/1348762/145599378-fa3c627f-67e7-45f5-aed4-6ad55630758c.png)
When connecting with a wrong header it causes an exception with a negative header.

**Comment by AngeloTadeucci** [comment]
This exception shouldn't stop the server from running so in the end it doesn't matter. The only issue is the FATAL level which we can't change.

Im closing this, what you think @darkvergus ?
