### ISSUE TITLE
Go to Warp in Quests not working

### ISSUE THREAD

**Issue by sharrman** [AlanMorel/MapleServer2#530]
- Some quests open a go to popup that does not work.

**Comment by AngeloTadeucci** [comment]
Which quest does that? @sharrman

**Comment by sharrman** [comment]
uest questID="50100820" name="Convening the World Security Council" for example

**Comment by sharrman** [comment]
![image](https://user-images.githubusercontent.com/88498938/152890743-81b1f2f2-6f56-4d29-863f-56da4498bde6.png)

**Comment by NeoTalon** [comment]
tbh, ik it works like the portal, when you click go, you should be teleported to said map.

just copypaste the functions of the portal, to work with the popup, and add an option to just not do it if the stay option is clicked.

that is probably my idea to make em work

**Comment by AngeloTadeucci** [comment]
@NeoTalon just implemented it man. just do it.

**Comment by AngeloTadeucci** [comment]
Fixed in #568
