### ISSUE TITLE
Enchant scrolls do not work

### ISSUE THREAD

**Issue by gwagwaflamingo** [AlanMorel/MapleServer2#635]
they just dont man
![image](https://user-images.githubusercontent.com/72739828/170188757-5fec43fb-5c52-4b5c-a0a2-2d37649ab004.png)

Socket scrolls are working as intended.

**Comment by AngeloTadeucci** [comment]
Maybe because they are not implemented?

**Comment by AngeloTadeucci** [comment]
They are implemented, changing this to bug
