### ISSUE TITLE
Mass dismantling not working

### ISSUE THREAD

**Issue by HoshinekoSanti** [AlanMorel/MapleServer2#679]
Steps to reproduce:
- Summon any epic or below item (this example uses 20302829 which makes it easier to get multiple weapons at once)
- Open all boxes
- Open the dismantling menu
- Click the "add" button after setting up epic or less tiered gear to be added
- The server will send packets but won't receive them for mass dismantling

![image](https://user-images.githubusercontent.com/106274631/174423367-1a540aba-3246-46fb-a1a7-d102a1cd881f.png)
![image](https://user-images.githubusercontent.com/106274631/174423383-53cd4d55-5a51-42c1-b412-e0e3ce4dbc03.png)

**Comment by AngeloTadeucci** [comment]
I can't seem to reproduce this

**Comment by HoshinekoSanti** [comment]
My bad, should be cosmetics, not gear
