### ISSUE TITLE
Server crash when jumping out of map

### ISSUE THREAD

**Issue by 810517583** [AlanMorel/MapleServer2#686]
I found some bug, when you [/event 4 1 0
 ] join the game,and then jump out the map.the mp2server will shut down
[16:37]
when you restart the server join the game you will in the game map and can move other maps,just use the commands [/m]

**Comment by 810517583** [comment]
After using "/event 456 and join the game" to join the game, your server will crash when you jump out of the map. After restarting the server, you will still be in the game map, but you cannot move other maps. Similarly, the server will crash and can only be moved to other maps with commands.
使用"/event 4 5 6 and join the game"加入小游戏后，当你跳出地图你的服务器会死机，重启服务器后你还会在游戏地图里，但是无法移动其他地图。同样服务器会死机，只能用命令移动到其他地图

**Comment by AngeloTadeucci** [comment]
@810517583 I can't reproduce the crash when jumping out the map. Please post a stack trace of the error.

**Comment by 810517583** [comment]
https://www.youtube.com/watch?v=rZ5ssjQ2NjY

**Comment by AngeloTadeucci** [comment]
I can't reproduce this.. :(

**Comment by 810517583** [comment]
That could be my problem or let someone else try it

**Comment by darkvergus** [comment]
just get sharr to do it!!!!!
