### ISSUE TITLE
How to remote server

### ISSUE THREAD

**Issue by maolincc** [AlanMorel/MapleServer2#739]
I tried to modify 127.0.0.1 localhost related files

However, the connection server displays 127.0.0.1:20001

**Comment by maolincc** [comment]
[WSPConnect_Hook] Address: xxxxxxx => Port: 8526
[WSPConnect_Hook] Patching to new address: xxxxxxx
[WSPConnect_Hook] Address: xxxxxxx => Port: 8526
[WSPConnect_Hook] Connecting to socket address: 127.0.0.1:20001   <-------

**Comment by darkvergus** [comment]
change your ip in the .env file to the public ip address you can find it here https://whatismyipaddress.com. 
![image](https://user-images.githubusercontent.com/1348762/187242898-9d52b097-9b48-47d6-8fee-8ca3735ce070.png)
![image](https://user-images.githubusercontent.com/1348762/187242930-7251084f-b24c-45c7-8c8d-c8ee791c2ad5.png)
Then you need to switch the ip in the client either by editing orion.ini inside your client folder with your public ip if no other port is changed.
![image](https://user-images.githubusercontent.com/1348762/187242326-bfc7b3dc-d43d-4768-bc4c-90e51a8f41f1.png)
![image](https://user-images.githubusercontent.com/1348762/187242373-4522c43b-725e-4e90-af7b-51649c5162b5.png)
or if it is just make a shortcut of the exe
![image](https://user-images.githubusercontent.com/1348762/187242457-261981cc-4aec-4270-85f6-a3337e46b086.png)
then going into the properties
![image](https://user-images.githubusercontent.com/1348762/187242509-860a8157-64cf-417a-bcf8-029f442b1578.png)
and adding to the target the following;
--ip=yourpublicip --port=yourport --nxapp=nxl --lc=EN
![image](https://user-images.githubusercontent.com/1348762/187242689-618e428a-ab15-46c0-bd3c-53e20e759e8b.png)

**Comment by maolincc** [comment]
thank you
