### ISSUE TITLE
Assassin Job Error weapon

### ISSUE THREAD

**Issue by wb121818778** [AlanMorel/MapleServer2#753]
[2022-09-15 23:47:55] [Error] MapleServer2.Types.Inventory: Failed to add item 2 to inventory 2, slot "LH" was already taken.
[2022-09-15 23:47:55] [Error] MapleServer2.Types.Inventory: Failed to add item 2 to inventory 2, slot "RH" was already taken.

**Comment by Kustale** [comment]
I've also seen this error. (I wrote the content of the error I encountered as it is, detailed and very long. Sorry)

1. When I first equip the basic weapon item (received from the tutorial) and cover another weapon item as it is (without dismounting it in advance), it will be equipped, but the basic weapon item will not be moved to the inventory window and will be overwritten. (Left and Right Hand respectively)
And when I change character or log out ([03:22:14] [ERR] Inventory: Failed to add item 1 to inventory 1, slot RH was already taken. (Enter) [03:22:14] [ERR] Inventory: Failed to add item 1 to inventory 1, slot LH was already taken.) An error occurred.
And when I log in again and open the character window, it is changed back to the default weapon item. (Other weapon items are missing. Equipped items do not appear in the inventory window.)
Here, if I put the weapon item in the character window back into the inventory and log in again, another weapon item that has disappeared is equipped.
(And if you put the equipped weapon item back into the inventory window, it will be dismounted normally and remain in the inventory window)
2. When I equip a weapon item with the left click of the mouse without dragging it from the inventory window to the character window, the two are not equipped individually, but both are equipped with the right hand. (The left hand is not attached)
An error occurred when I logged out ([03:39:05] [ERR] Inventory: Failed to add item 1 to inventory 1, slot RH was already taken.).
And when I log in again, the weapon item attached to the right hand disappears and is replaced with the basic weapon item.
However, one weapon item that is all covered by the right hand is put back into the inventory window.
And, when I move this basic weapon item to the inventory window and reconnect, the weapon item I equipped earlier appears, but the left hand side is not. (The left hand side is moved to the inventory window as described above)

* The above error does not occur with two-handed weapon items. (I haven't tested one-handed weapons or two-handed weapons yet)

Helped by a translator.
