### ISSUE TITLE
Incorrect Gear

### ISSUE THREAD

**Issue by venimo** [AlanMorel/MapleServer2#763]
**Describe the bug**
When you made de customization of the character when creating and after that pressing Create, filling in a name and press OK, it says: "Incorrect Gear".

**To Reproduce**
Example:
1. Logging in the Game
2. Choosing a class you want to be in my case, Assassin.
3. Customize the character to my liking.
4. Pressing the yellow button with the text "Create".
5. Fill in a name.
6. Press OK.
7. Now you get the error: "Incorrect Gear".

**Expected behavior**
After pressing ok you should get into the game normally.

**Comment by Clockworkx** [comment]
Can you show a picture of the character where the error occured? I think it was a certain gear piece that causes this error. Never had the error myself

**Comment by venimo** [comment]
> Can you show a picture of the character where the error occured? I think it was a certain gear piece that causes this error. Never had the error myself

Doesn't matter how you customize it actually, I also did random clothing etc. Also tried different classes or names.

**Comment by wb121818778** [comment]
assassin professional weapons right-click to equip the old weapons will not return to the backpack
Error！
[2022-09-20 07:46:01] [Error] MapleServer2.Types.Inventory: Failed to add item 3 to inventory 3, slot "LH" was already taken.
[2022-09-20 07:46:01] [Error] MapleServer2.Types.Inventory: Failed to add item 3 to inventory 3, slot "RH" was already taken.
