### ISSUE TITLE
Can't modify the number of SpawnMobs?

### ISSUE THREAD

**Issue by wb121818778** [AlanMorel/MapleServer2#766]
private void SpawnMobs(IFieldObject<MobSpawn> mobSpawn)
    {
        foreach (NpcMetadata mob in mobSpawn.Value.SpawnMobs)
        {
            if (mob.Name == "Constructor Type 13")
            {
                continue;
            }
            int groupSpawnCount = mob.NpcMetadataBasic.GroupSpawnCount; // Spawn count changes due to field effect (?)
            if (mobSpawn.Value.Mobs.Count + groupSpawnCount > mobSpawn.Value.MaxPopulation)
            {
                break;
            }

            for (int i = 0; i < groupSpawnCount; i++)
            {
                RequestMob(mob.Id, mobSpawn);
            }
        }
    }

**Comment by AngeloTadeucci** [comment]
#765
