### ISSUE TITLE
Cannot save changes at first when changing makeup's position with free move

### ISSUE THREAD

**Issue by gwagwaflamingo** [AlanMorel/MapleServer2#776]
Player cannot save changes after changing makeup's position for the first time. Only applied to free move, and not using one of the preset positions.

**To Reproduce**
1. Go to beauty salon and speak to Ren
2. Move your makeup's position manually (i.e don't use one of the presets)
3. No changes will be registered, and the player cannot save their changes
4. Move the makeup's position manually a second time
5. The changes will be registered, and the player can save them as expected

**Expected behavior**
1. Go to beauty salon and speak to Ren
2. Move your makeup's position manually (i.e don't use one of the presets)
3. The changes will be registered, and the player can save them as expected

**Comment by Zintixx** [comment]
I'm not sure if this is even fixable. Seems more like a client issue.
