### ISSUE TITLE
In some maps, quests do not complete.

### ISSUE THREAD

**Issue by Kustale** [AlanMorel/MapleServer2#803]
**Describe the bug**

In some dungeons, quests do not complete.

**To Reproduce**

1. Enter Golden Tower 8F
2. Scenario progression.
3. Defeat Kokun.
4. Quest progress.

**Expected behavior**

The quest window closes and does not complete.

**Screenshots**

https://drive.google.com/file/d/167_DS7K9YqHXERcG_Mwpo7bR-HkpsA38/view?usp=sharing

**Stack trace of the error**

No special errors were found.

**Latest commit id**

**Comment by Kustale** [comment]
Reasons for some maps: Most of the quests are possible to complete.
(* Sorry for continuing to report this error, if this is being corrected.)

**Comment by AngeloTadeucci** [comment]
This is not really a bug but quests conditions need to manually implemented and they are missing at the moment.

**Comment by Kustale** [comment]
> This is not really a bug but quests conditions need to manually implemented and they are missing at the moment.
> 
> * [Quests #62](https://github.com/AlanMorel/MapleServer2/issues/62)

Oh, I will cancel this bug report.

**Comment by Kustale** [comment]
> This is not really a bug but quests conditions need to manually implemented and they are missing at the moment.
> 
> * [Quests #62](https://github.com/AlanMorel/MapleServer2/issues/62)

Oh, I will cancel this bug report.
