### ISSUE TITLE
I tried this server on linux.

### ISSUE THREAD

**Issue by Kustale** [AlanMorel/MapleServer2#807]
(This attempt was because I couldn't afford to buy Windows to run the server. [Joke])
Of course, I can't use what I compiled on Windows, so I compile it by doing git again on Linux.
Compilation is the same as in Windows.

Once it works fine:

GameDataParser
MapleWebServer

However, this server is not working.
MapleServer2 error:

Unhandled exception. System.TypeInitializationException: The type initializer for 'MapleServer2.MapleServer' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll: cannot open shared object file: No such file or directory
   at Costura.AssemblyLoader.SetErrorMode(UInt32 uMode)
   at Costura.AssemblyLoader.InternalPreloadUnmanagedLibraries(String tempBasePath, IList`1 libs, Dictionary`2 checksums)
   at Costura.AssemblyLoader.PreloadUnmanagedLibraries(String hash, String tempBasePath, List`1 libs, Dictionary`2 checksums)
   at Costura.AssemblyLoader.Attach()
   at .cctor()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at MapleServer2.MapleServer.Main() in /home/kustale/MapleServer2/MapleServer2/MapleServer.cs:line 50
   at MapleServer2.MapleServer.<Main>()

It looks like it can only run on Windows.

**Comment by AngeloTadeucci** [comment]
MapleServer2 has a dependency called "Maple2.PathEngine" which only runs on windows

**Comment by Kustale** [comment]
> MapleServer2 has a dependency called "Maple2.PathEngine" which only runs on windows

Aha, when I opened Maple.PathEngine, that commercial library exists.
I can see the PathEngine in the source code.
This is supposed to be a library for reading tok files and creating maps. (The tok file is visible in the example file. It is the same as seeing the tok file when GameDataParser is executed.)
It seems that this is only supported on Windows.
