### ISSUE TITLE
The file cannot be extracted.

### ISSUE THREAD

**Issue by Kustale** [AlanMorel/MapleServer2#818]
**Describe the bug**

Error when using GameDataParser.

**To Reproduce**

1. dotnet.exe run --project ./GameDataParser/GameDataParser.csproj -c debug
2. wait...

**Expected behavior**

Error.

**Screenshots**

![46357373](https://user-images.githubusercontent.com/113628110/210159112-8df199bf-c867-423a-90d7-9d136073a497.jpg)

**Stack trace of the error**

Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Maple2.File.IO.Crypto.Stream.PackStreamVer2.InitFileList(BinaryReader reader)
   at Maple2.File.IO.M2dReader..ctor(String path)
   at GameDataParser.Files.MetadataResources..ctor() in D:\MapleServer2-First\GameDataParser\Files\Resources.cs:line 18
   at GameDataParser.Program.Main(String[] args) in D:\MapleServer2-First\GameDataParser\Program.cs:line 39
   at GameDataParser.Program.<Main>(String[] args)

**Latest commit id**

**Comment by Kustale** [comment]
Well, the modified file is causing the error...
Tried with the original file and no error occurs.

**Comment by Kustale** [comment]
I've found the reason.
I worked on adding some languages to xml.m2d, but I inserted a file in the middle and compressed it as it is, but there was a problem with that file.
I deleted that file and recompressed it and it worked fine.

**Comment by Kustale** [comment]
Solved this issue too.

It turns out that the difference between the m2d compression program.
I use ms2tool instead of orion2-repacker to save time.

I get an error when I use a file compressed with ms2tool.
If I use a file compressed with orion2-repacker, it's normal.

**Comment by AngeloTadeucci** [comment]
Yeah we dont know why ms2tools doesn't compress correctly... at least orion2 works
